package sv.edu.udb.hibernate;
// Generated 09-21-2017 08:46:35 AM by Hibernate Tools 4.3.1



/**
 * Datosempleados generated by hbm2java
 */
public class Datosempleados  implements java.io.Serializable {


     private Integer id;
     private String nombres;
     private String apellido;
     private int edad;
     private String telefono;
     private String direccion;

    public Datosempleados() {
    }

	
    public Datosempleados(String nombres, String apellido, int edad) {
        this.nombres = nombres;
        this.apellido = apellido;
        this.edad = edad;
    }
    public Datosempleados(String nombres, String apellido, int edad, String telefono, String direccion) {
       this.nombres = nombres;
       this.apellido = apellido;
       this.edad = edad;
       this.telefono = telefono;
       this.direccion = direccion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }




}


